#!/usr/bin/env python3
"""Generate (or --check) skills/INDEX.md from every conforming skill.

    python3 scripts/index-skills.py           # regenerate skills/INDEX.md
    python3 scripts/index-skills.py --check   # fail if the committed index is stale

See scripts/skills.py for the implementation and docs/agents/skills.md for usage.

Why this thin wrapper exists (issue #55 audit): ``index`` is a subcommand of
``scripts/skills.py``, but this clone is a *stable, named* entry point referenced
by CI (``validate-skills.yml``), ``CLAUDE.md``, ``README.md``, the ADRs, and the
``AUTO-GENERATED by scripts/index-skills.py`` header it stamps into
``skills/INDEX.md``. Deleting it would touch ~a dozen call sites — moving
complexity, not concentrating it — so the deletion test keeps it. The logic
lives in ``scripts/skills.py``; this file is the named target only.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import skills  # noqa: E402

if __name__ == "__main__":
    sys.exit(skills.main(["index", *sys.argv[1:]]))
